### ISSUE TITLE
Bug: V2 GUI freezes playing back recorded .txt

### ISSUE THREAD

**Issue by topant** [OpenBCI/OpenBCI_GUI#120] opened 2017-02-05 19:26 UTC
Hi,

I use OpenBCI GUI v2.1 x64 and Ultracortex 8-channel Mark III on Win7 x64.
Record EEG signals and save it locally works fine but when I try to playback signals from file, OpenBCI GUI freeze.

If I try to open file (.txt or .edf) on OpenBCI GUI v1, everything works fine.

Any ideas what is wrong?

**Comment by topant** [comment] 2017-02-05 19:30
[OpenBCI-RAW-2017-02-04_22-33-00.txt](https://github.com/OpenBCI/OpenBCI_GUI/files/753217/OpenBCI-RAW-2017-02-04_22-33-00.txt)

**Comment by topant** [comment] 2017-02-05 19:32
[OpenBCI-RAW-2017-02-04_22-33-00 - ORG.txt](https://github.com/OpenBCI/OpenBCI_GUI/files/753220/OpenBCI-RAW-2017-02-04_22-33-00.-.ORG.txt)

**Comment by aj-ptw** [comment] 2017-02-05 21:08
Hi @topant thanks for the reports!

I moved the `.edf` over to #121 and tagged you in it.

Totally seeing this error on my end too! I'll patch it and let you know here when it's fixed!

**Comment by topant** [comment] 2017-02-06 08:59
All right, thanks for info.

**Comment by aj-ptw** [comment] 2017-02-07 18:07
working on this right now

**Comment by aj-ptw** [comment] 2017-02-07 18:27
Looks like the problem is [in ControlPanel.pde](https://github.com/OpenBCI/OpenBCI_GUI/blob/master/OpenBCI_GUI/ControlPanel.pde#L152)

```java
...
else if(newDataSource == DATASOURCE_PLAYBACKFILE){
      updateToNChan(8);
    } 
...
```

**Comment by aj-ptw** [comment] 2017-02-07 18:55
@topant the problem was solved on the [original GUI here](https://github.com/OpenBCI/OpenBCI_Processing/pull/49)

**Comment by aj-ptw** [comment] 2017-02-07 19:21
#124 fixes this issue. it's in development and will be merged soon. will close this issue when merged with master. for now it's in the development branch!

**Comment by topant** [comment] 2017-02-13 09:54
Hi,

when will you release a new version of OpenBCI GUI with these fixes?

**Closed** 2017-02-16 18:10 UTC
Labels: bug, in progress

**Comment by aj-ptw** [comment] 2017-02-16 18:43
Hi running out of time for this week but was able to get a pre-release up https://github.com/OpenBCI/OpenBCI_GUI/releases/tag/v2.1.2 so please try that and let me know!

**Comment by aj-ptw** [comment] 2017-03-16 18:23
@topant the new GUI has been released, please download the new gun from either openbci.com
