### ISSUE TITLE
v4.1.3-beta.3 - not working: Unable to Load Java Runtime Environment (Sierra OS)

### ISSUE THREAD

**Issue by krisztian-hofstadter-tedor** [OpenBCI/OpenBCI_GUI#563] opened 2019-07-18 15:40 UTC
hi, 

was trying to test the newest release on Sierra but couldn't get it started:

'Unable to Load Java Runtime Environment' in pop up window.

more here if needed: https://youtu.be/T_WWrL1HDm0

thanks! k

**Comment by krisztian-hofstadter-tedor** [comment] 2019-07-18 15:41
hi, 

was trying to test the newest release on Sierra but couldn't get it started:

'Unable to Load Java Runtime Environment' in pop up window.

more here if needed: https://youtu.be/T_WWrL1HDm0

thanks! k

**Comment by retiutut** [comment] 2019-07-22 15:46
Please just update your Mac. Supporting older versions of OS is a nightmare.

Mac OS Sierra Initial release: September 20, 2016; 2 years ago

**Comment by retiutut** [comment] 2019-07-22 15:53
@krisztian-hofstadter-tedor Please start opening the Console Log in these videos. It's very hard to understand what is happening without seeing the Console Log.

**Comment by retiutut** [comment] 2019-07-22 15:56
@krisztian-hofstadter-tedor As a consolation, I have seen the signal drop to zero sometimes as you have described in this video.

**Comment by krisztian-hofstadter-tedor** [comment] 2019-07-22 16:04
thanks Richard, 
- I'll try Direct mode; 
- update an OS - to Mojave; 
(keep the logs in mind for next time);

then, maybe my other issue with the 50hz jumps with wifi will be sorted as well; 
(would be good to find someone who works with cyton and wifi - this person could let me know firmware, os version, gui version, etc...) .. I think I am just worried that maybe one of the boards (cyton or wifi) is damaged. 

Thanks. k

**Comment by retiutut** [comment] 2019-07-22 16:11
@krisztian-hofstadter-tedor Let's focus on the simple java runtime error. Update your OS and let me know if the problem still happens.

There doesn't seem to be anything wrong with the boards.

This issue of dropped packets and artifacts is an extremely difficult issue: https://github.com/OpenBCI/OpenBCI_GUI/issues/231. In fact, this is what prompted me to start working on the GUI almost a year ago. If you want less dropped packets, use Cyton without the WiFi shield. I'm not interested in discussing this as it is "in progress".

**Comment by krisztian-hofstadter-tedor** [comment] 2019-07-22 17:31
aha. thanks for the clarification.

**Comment by krisztian-hofstadter-tedor** [comment] 2019-07-23 11:57
@retiutut

I have the same issue in a fresh Mojave install. Tried a few things, maybe this short video helps: 

https://youtu.be/eGPmWjdi73I

cheers! k

**Comment by retiutut** [comment] 2019-07-23 15:14
@krisztian-hofstadter-tedor Possibly caused by me building the app using an old version of Processing!

**Comment by retiutut** [comment] 2019-07-23 19:52
This issue has been replicated!

**Comment by retiutut** [comment] 2019-07-23 21:44
@krisztian-hofstadter-tedor Me and @leanneapichay have found a fix!!!!! 🔥🔥🔥

First Solution:
- Java 8 appears to have been updated to Version 8 Update 221, Release date July 16, 2019 https://www.java.com/en/download/
- Download and update Java, should allow the build you have already to run!

Second Solution:
- I/We build the OpenBCI_GUI.app and include the Java Runtime Environment, but this makes the App package much larger

**Comment by krisztian-hofstadter-tedor** [comment] 2019-07-23 21:55
@retiutut 

Cheers! I'll test 1st solution asap. k

**Comment by retiutut** [comment] 2019-07-26 22:48
@krisztian-hofstadter-tedor I've been told that 4.1.3-beta.3-BUILD-4-SIGNED works without having to reinstall java.

**Comment by retiutut** [comment] 2019-07-26 22:50
Closing this issue. @krisztian-hofstadter-tedor I'm about to bump the version to a stable release of 4.1.3, let me know if this happens again.

**Closed by retiutut** 2019-07-26 22:50 UTC
Labels: Workable Fix Exists, bug

**Comment by krisztian-hofstadter-tedor** [comment] 2019-07-29 15:42
works without JAVA, thanks.
