### ISSUE TITLE
GUI is unusable on high DPI screen

### ISSUE THREAD

**Issue by patrickmineault** [OpenBCI/OpenBCI_GUI#145] opened 2017-03-17 19:13 UTC
I use a Dell XPS 13 on Ubuntu, which has a retina-like display (3200x1800). The OpenBCI GUI doesn't scale appropriately, and the interface elements are so small as to be unusable:

![screenshot from 2017-03-17 12-05-39](https://cloud.githubusercontent.com/assets/3516539/24059131/133989d0-0b0b-11e7-9810-7a53b285b5fb.png)

 This is a common occurrence on Java and Processing-based programs, and most programs (Processing, Arduino, RStudio) have some setting to scale the interface. In the case of Arduino, it pretty much works (shown here at 200%), although Processing only partially scales the interface. Here are some related bugs from Processing:

https://github.com/processing/processing/issues/4183
https://github.com/processing/processing/issues/4895

Just adding a setting to scale the interface would work, I think.

**Comment by aj-ptw** [comment] 2017-03-24 13:32
@patrickmineault thanks for the report! This is an important fix, will dig in.

**Comment by aj-ptw** [comment] 2017-03-24 13:32
whoops did not mean to close that

**Comment by aj-ptw** [comment] 2017-06-09 17:18
This is bigger than I though to implement. Working to figure out how long it will take!

**Comment by aj-ptw** [comment] 2017-06-27 14:43
Because the upstream processing is taking forever to fix this, going to address this...

**Comment by aj-ptw** [comment] 2017-06-27 19:30
@conorrussomanno I made some progress on this, there is a problem right now with mouse hover over. Can you please boot up this version of the GUI and adjust the scale factor, you'll see how to do it really quickly, it's self explanatory. Currently need to move the hover over when buttons update their size. If you want to use the new function `guiScale(float)` or `guiScaleInt(int)` call them in the draw loops of the widgets and such, not on initialization!

**Comment by aj-ptw** [comment] 2017-09-07 13:07
@patrickmineault there is an option if you right click on the executable -> properties -> compatibility -> don't do high DPI scaling (or something similar) that should solve this problem for now!

**Comment by daniellasry** [comment] 2019-04-28 21:02
The root of the issue is that [processing uses java 8, and it's not looking like they will update it anytime soon.](https://github.com/processing/processing/wiki/Supported-Platforms#java-versions)

Java 8 is telling the OS that it is DPI aware, [but doesn't scale UI elements](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display).

On windows, we can work around the issue by [forcing the OS to scale the app](https://github.com/OpenBCI/OpenBCI_GUI/pull/503).
(it will look blurry but readable)

On linux, there is no way to force scaling. The hack I found that works, is using this script:
https://github.com/kaueraal/run_scaled

**Comment by retiutut** [comment] 2019-05-17 00:22
See @daniellasry's comments above. Closing this issue.

**Comment by wjcroft** [comment] 2019-05-19 06:54
@retiutut and @daniellasry , the current 'footnote' in the GUI doc says only this, very tersely:

> If you have a high DPI screen and are running windows 10, you may notice that the GUI is hard to see, and nothing seems to scale correctly. Select Change high DPI Settings and on the bottom drop down box, change from Application to System (Enhanced).

And that statement has apparently confused at least one high DPI user (see post near bottom):

http://openbci.com/forum/index.php?p=/discussion/2128/can-the-gui-playback-recordings-gui-on-high-dpi-screens

Here is an illustrated article showing the setting in detail:

https://www.windowscentral.com/how-improve-app-dpi-scaling-enabling-system-enhanced-feature-windows-10

Is this something we should link to from the docs page? I have not heard back from the user on the above thread.  Not sure if this will solve his issue yet. He claims on the forum thread that he tried to follow directions, but not sure if he connected the dots to open the Properties on the GUI app file.

**Comment by daniellasry** [comment] 2019-05-19 13:32
hey @wjcroft ! That's supposed to be fixed in 4.1.2 (and still looks fixed after a quick test). I'm puzzled to why this user still had the issue with 4.1.2. I'll go ahead and ask for a screenshot.

**Comment by wjcroft** [comment] 2019-05-19 17:59
Daniel, thanks much. Apparently zfmeng was able to adjust the Properties dropdown to fix it. I asked him to repost his screenshot from before the fix. I think zfmeng's confusion was mostly over our terse instructions in the docs file. It does not mention the GUI exe explicitly, nor that this is done on the Properties dialog box. Thanks again for following up on the forum. You should get an email notification if/when he reposts his screenshot.

**Comment by retiutut** [comment] 2019-05-20 19:44
The Docs have been updated to reflect the information in the Issue. Also included pictures for Windows users.

**Comment by wjcroft** [comment] 2019-05-20 19:59
Richard (and Daniel), thanks so much!

> One nitpick, your text in the Docs page starts out: "If you have a high DPI screen and are running Windows 10, you may notice that the GUI is hard to see, and nothing seems to scale correctly. Right click on OpenBCI_GUI.exe and select Properties. The following window should pop up: ..."

However, zfmeng on the forum had the problem that he attempted to change the Properties WHILE the GUI was running. The GUI should be closed if running (and hard to see / poor scaling). THEN the Property box changed, then the GUI restarted.

Zfmeng stated clearly that he changed the property back and forth and did not see any changes. This is why.

Regards, William

**Comment by retiutut** [comment] 2019-05-20 20:08
@wjcroft Ok that's the last part. Still need to add that but I have to leave my desk right now.

**Comment by retiutut** [comment] 2019-05-21 02:39
Ok updated the docs to say close the GUI first.

**Comment by wjcroft** [comment] 2019-05-21 02:44
Hey, thanks much Richard. I was surprised when Zfmeng was at first not able to adjust the Properties, even after giving him the Windows Central article link. So being this explicit will help future users.

**Comment by retiutut** [comment] 2019-05-21 02:45
Could even be clearer if the screenshots start having annotations (easy to do on Mac). Closing this issue for now, unless more information arises.

**Closed by retiutut** 2019-05-21 02:45 UTC
Labels: bug, linux, wontfix
