### ISSUE TITLE
Linux with CSR 4.0 dongle: Code 412Error: Please turn blue tooth on.

### ISSUE THREAD

**Issue by hack-r** [OpenBCI/OpenBCI_GUI#200] opened 2017-08-23 01:10 UTC
Hi,

I can see the Ganglion using `hcitool`'s `lescan` over the CSR 4.0 dongle. However, the GUI app throws the 

> Code 412Error: Please turn blue tooth on.

error. My guess is that it only uses `hci0`, which is the built-in adapter instead of `hci1` which is the dongle (?). Both the builtin adapter and the dongle are active and support BLE scanning though. I tried turning off `hci0` through `hciconfig` temporarily, but that didn't help. 

My OS is Ubuntu. No BT devices appear in the GUI window. 
<pre>
./OpenBCI_GUI
Launching application from local data dir
OpenBCI_GUI: hubStart: OS Detected: Linux
Welcome to the Processing-based OpenBCI GUI!
Last update: 12/20/2016
For more information about how to work with this code base, please visit: http://docs.openbci.com/OpenBCI%20Software/
Graphics & GUI Library: ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
attempting to load images for presentation...
DONE loading images!
Instantiating Ganglion object...
GanglionSync: clientEvent: handshake complete
OpenBCI_Ganglion: processStatus: Started Successfully
Code 412Error: Please turn blue tooth on.
OpenBCI_GUI: mousePressed: mouse pressed
CPmousePressed
click
OpenBCI_GUI: mousePressed: mouse pressed
CPmousePressed
Code 412Error: Please turn blue tooth on.
^CSHUTDOWN HOOK
Client got end-of-stream.
Killed:  5942 pts/0    00:00:00 GanglionHub
Killed:  5945 pts/0    00:00:00 GanglionHub
SHUTDOWN HUB
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 2/2, reusable (open, marked uncloseable): 0, pending (open in creation order): 2)
X11Util: Open X11 Display Connections: 2
X11Util: Open[0]: NamedX11Display[:0, 0x7fb85c000e80, refCount 1, unCloseable false]
X11Util: Open[1]: NamedX11Display[:0, 0x7fb85c00e1c0, refCount 1, unCloseable false]

**Comment by aj-ptw** [comment] 2017-08-26 18:19
Is this problem still persisting?

**Comment by hack-r** [comment] 2017-08-26 19:05
@aj-ptw  Hi AJ. Yes, it is. Ubuntu 16.

**Comment by aj-ptw** [comment] 2017-08-26 19:08
@hack-r 

Okay, first, let's use **not** use the CSR 4.0 dongle.

Then try the GUI. This should work if your computer is BLE ready.

If this fails, then please follow the instructions found on the [`noble`](https://github.com/sandeepmistry/noble#ubuntudebianraspbian) page?

**Comment by aj-ptw** [comment] 2017-08-26 19:11
You can also try hitting the refresh list button

**Comment by aj-ptw** [comment] 2017-12-13 15:35
Pretty sure the problem is you did not use `sudo`. Closing this for now.

**Closed by aj-ptw** 2017-12-13 15:35 UTC

**Comment by aj-ptw** [comment] 2018-04-14 18:33
Not as far as I know! I’m not a Linux guy though, any ideas?

**Comment by brylie** [comment] 2018-04-15 07:43
Not sure, it just seems that other Bluetooth applications work without sudo permissions. It's not a big deal, so long as end users know what to expect. I only solved this issue because I found  the relevant bug report and read through the whole discussion.
