### ISSUE TITLE
GUI hangs when trying LSL and when played by Processing IDE, hub does not work

### ISSUE THREAD

**Issue by marcelus** [OpenBCI/OpenBCI_GUI#316] opened 2018-03-16 03:43 UTC
## Problem

I'm trying to use my Ganglion with OpenVibe. Now, I'm stuck trying to stream the data to LSL. From the ".exe" GUI, it just hangs when I press to start LSL. So I went to the Processing IDE to get some console message, but when I try to use it from the IDE, the GUI shows the message: "Please launch OpenBCI Hub prior to launching this application. Learn at docs.openbci.com". The Hub is already running as administrator.

## Expected 

Connect to OpenVibe via LSL streaming.

## Operating System and Version

Windows 10 Home Single Language

## GUI Version

3.2.0

## Running standalone app

Both

## Type of OpenBCI Board

Ganglion

## Are you using a WiFi Shield?

No

**Comment by aj-ptw** [comment] 2018-03-22 17:00
Maybe you have two versions of the hub running? Be sure to have no hubs running, then start one hub and then the openbci gui from processing.

**Comment by marcelus** [comment] 2018-03-23 12:38
![openbcihub1](https://user-images.githubusercontent.com/5081339/37829229-09c06388-2e7d-11e8-88b1-71f0cba54bd5.png)
![openbcihub2](https://user-images.githubusercontent.com/5081339/37829420-ac5c7bcc-2e7d-11e8-8eb0-c721fd8cf664.png)

I started OpenBCI_Hub only once and it started two process. Then I've opened the processing and started the GUI from there. Still same issue.
Also, I was running everything in administrator mode.

**Comment by marcelus** [comment] 2018-03-23 13:26
Looking at the code, this is the conditions to the error:

`if (newDataSource != DATASOURCE_SYNTHETIC && newDataSource != DATASOURCE_PLAYBACKFILE && !hub.nodeProcessHandshakeComplete) {`

This line 157 from ControlPanel.pde. I've tried to force "hub.nodeProcessHandshakeComplete" as true when instantiating hub. It goes through the error message and opens the menu, but freezes at line 1201 from the GUI code:

`for (int i = 0; i < hub.deviceList.length; i++) {`

It giver a NullPointerException. Probably cause it's not really connected to the hub.

**Comment by aj-ptw** [comment] 2018-03-23 15:20
There is an issue where the two hubs are open. Force close both and be sure to only start the hub once.

**Comment by marcelus** [comment] 2018-03-23 17:12
I've already do this a couple of times. And same results :/

**Comment by aj-ptw** [comment] 2018-03-23 17:18
Starting the hub starts two processes?

**Comment by aj-ptw** [comment] 2018-03-23 17:20
I have not heard of this problem :(

**Comment by aj-ptw** [comment] 2018-03-23 17:21
Try force closing the hub with the higher process ID

**Comment by marcelus** [comment] 2018-03-23 18:15
Tried to close the process with less memory consumption and start the GUI from processing. Same issue.
And when I try to close the process with more memory consumption it kills the other one automatically.
![openbcihub3](https://user-images.githubusercontent.com/5081339/37846656-0d928542-2ead-11e8-95dd-f8ebfd5aeb12.png)

**Comment by sidharthanup** [comment] 2018-03-29 18:37
![hubimg](https://user-images.githubusercontent.com/21989660/38106871-00ca894e-33ae-11e8-8843-0894b33289e5.png)

The OpenBCI_GUI folder is for the standalone app. 
![hubimg2](https://user-images.githubusercontent.com/21989660/38106943-30426d36-33ae-11e8-8a73-1e64449860c9.png)
![hubimg3](https://user-images.githubusercontent.com/21989660/38106957-37777402-33ae-11e8-89e9-8b08df2ec9d6.png)

**Comment by sidharthanup** [comment] 2018-03-29 18:48
![hubimg4](https://user-images.githubusercontent.com/21989660/38107426-8fd0394e-33af-11e8-9548-0eb2c2ab6039.png)
![hubimg5](https://user-images.githubusercontent.com/21989660/38107429-90025b90-33af-11e8-9e27-7fd436f912df.png)
![hubimg6](https://user-images.githubusercontent.com/21989660/38107430-9034c51c-33af-11e8-9ec6-ee07a78a7f4e.png)
This is when I run the sketch

**Comment by sidharthanup** [comment] 2018-03-29 20:38
Ya the same thing for me as well.

**Comment by aj-ptw** [comment] 2018-04-02 12:12
Looks like the hub might just be running two processes classified by the operating system, so perhaps the two hub processes running is not the problem.

Are any of you running a proxy? Or some software that could prevent the internal communications from working on the mac? 

Did you see a pop-up asking if you would allow private communications for the OpenBCI Hub?

**Comment by aj-ptw** [comment] 2018-04-04 12:47
hey im running hub on my windows machine and it's totally cool that two processes open up when running the hub, this is not the problem

**Comment by aj-ptw** [comment] 2018-04-04 12:56
looks like i have three processes running when the hub is in use by the GUI, are y'all running these hubs as admin?

**Comment by marcelus** [comment] 2018-04-04 13:06
Hey, about the proxy, I'm not running any.
I think that it did poped up a window asking about permitions and stuff, but I granted all access to it.

And yes, I'm running everything as admin :p (HUB, Processing, GUI)

**Comment by aj-ptw** [comment] 2018-04-04 13:12
I can see that the GUI is not able to talk to the hub, so something is blocking this connection. I wonder what it could be. As far as I know both of those check boxes need to be hit. Is this problem duplicating on other Windows computers for you?

**Comment by marcelus** [comment] 2018-04-04 13:27
![image](https://user-images.githubusercontent.com/5081339/38310369-be75c6c8-37f2-11e8-8a88-af0f2590f675.png)
seem to be fine. Just opened the Hub and then ran the python script.

**Comment by aj-ptw** [comment] 2018-04-04 13:28
ooouuuu 0.o it's the processing file not being able to talk to the hub!!!

okay! cool we are totally getting somewhere

**Comment by marcelus** [comment] 2018-04-04 13:29
Nice :D

**Comment by aj-ptw** [comment] 2018-04-04 13:35
Okay! same thing, start the hub (if it's not already) and don't run the GUI in standalone or processing and then run [this processing file](https://github.com/OpenBCI/OpenBCI_Hub/blob/master/tests/status.pde).

Expected output:
```processing
q,200,;
q,200,;
```

_note_ idk why it's printing twice but status is good

**Comment by aj-ptw** [comment] 2018-04-04 13:42
thanks for your help btw

**Comment by sidharthanup** [comment] 2018-04-04 13:58
![pde_test](https://user-images.githubusercontent.com/21989660/38311995-2b1c850a-383e-11e8-8608-31530881d961.png)
Status is good

**Comment by aj-ptw** [comment] 2018-04-04 14:04
Okay next up, [uncomment this line](https://github.com/OpenBCI/OpenBCI_GUI/blob/master/OpenBCI_GUI/InterfaceHub.pde#L296) and run the GUI from processing!

**Comment by sidharthanup** [comment] 2018-04-04 14:28
Ran it after uncommenting the line in InterfaceHub.pde 
![test2](https://user-images.githubusercontent.com/21989660/38313496-ce688d32-3841-11e8-99de-b2787d28ba03.png)
Couldn't find any changes

**Comment by aj-ptw** [comment] 2018-04-04 14:32
show me all of the output from the processing windows

**Comment by sidharthanup** [comment] 2018-04-04 14:39
![test3](https://user-images.githubusercontent.com/21989660/38314495-f6c87808-3843-11e8-8c35-845e10839cef.png)

**Comment by marcelus** [comment] 2018-04-04 17:08
I got the same output as sidharthanup printed.

Then I uncommented line 296 from InterfaceHub.pde and here goes the screenshot:
![image](https://user-images.githubusercontent.com/5081339/38322714-9f973d8a-3811-11e8-90cd-d4814170fd99.png)

**Comment by marcelus** [comment] 2018-04-04 17:11
Ops, I didn't see that there was already an answer.
But yet, same results here.

**Comment by aj-ptw** [comment] 2018-04-04 17:49
Try using an older version of Processing like 3.3.4, maybe 3.3.7 is broken?

**Comment by sidharthanup** [comment] 2018-04-04 18:28
Yes! Its working now
![test4](https://user-images.githubusercontent.com/21989660/38326571-bce8e472-3863-11e8-8cb3-2725bd4cc03b.png)
Never occurred to me to try an older version..Thank you!

**Comment by marcelus** [comment] 2018-04-09 19:18
Sorry for de delayed answer. I was getting a Null Pointer Exception, but I found out that the error was from a piece of code that I had modified.
After getting it back to the original code, it worked out with Processing 3.3.6.

Thanks!! 😄 😄

**Comment by trtnk** [comment] 2018-04-19 05:37
I am having similar problems as well. I want your help.

* Enviroment
    - OS: windows 10
    - Proccessing version: 3.3.4
    - Type of board: Cyton
    - WiFi use: No
    - Proxy use: Yes

In this environment, when I run OpenBCI_GUI from Proccesing and click Live(from Cyton),  
It will look like the image below.

![openbci_false1](https://user-images.githubusercontent.com/38518862/38973066-df57aef4-43de-11e8-8441-03d11459f415.png)

I show the image of the error message displayed by Processing also.  
OpenBCIHub is running in administrator mode.

![openbci_error](https://user-images.githubusercontent.com/38518862/38973080-eea85aca-43de-11e8-9f1e-a8ce15de244c.png)

Is Proxy the cause?

**Comment by trtnk** [comment] 2018-04-23 02:59
Thanks for speedy response to the question.

I tried STANDALONE application, I got below message at the application window of OpenBCI_GUI.
```
Please launch OpenBCI Hub prior to launching this application. Learn at docs.openbci.com
```

When I tried running the OPENBCI GUI from Procissing IDE, I got below message at console of Processing IDE. And it came up to the same result as the STANDALONE application.
```
Could not parse -1 for --display
Welcome to the Processing-based OpenBCI GUI!
Last update: 9/5/2016
For more information about how to work with this code base, please visit: http://docs.openbci.com/OpenBCI%20Software/
Graphics & GUI Library: ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
attempting to load images for presentation...
DONE loading images!
OpenBCI_GUI::Setup: Is RX mulitcast: false
OpenBCI_GUI::Setup: Has RX joined multicast: false
java.net.SocketException: Malformed reply from SOCKS server
    at java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:129)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:459)
    at java.net.Socket.connect(Socket.java:589)
    at java.net.Socket.connect(Socket.java:538)
    at java.net.Socket.<init>(Socket.java:434)
    at java.net.Socket.<init>(Socket.java:211)
    at processing.net.Client.<init>(Unknown Source)
    at OpenBCI_GUI$Hub.startTCPClient(OpenBCI_GUI.java:12568)
    at OpenBCI_GUI$Hub.<init>(OpenBCI_GUI.java:12544)
    at OpenBCI_GUI.systemUpdate(OpenBCI_GUI.java:982)
    at OpenBCI_GUI.draw(OpenBCI_GUI.java:482)
    at processing.core.PApplet.handleDraw(PApplet.java:2439)
    at processing.opengl.PSurfaceJOGL$DrawListener.display(PSurfaceJOGL.java:849)
    at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
    at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
    at jogamp.opengl.GLAutoDrawableBase$2.run(GLAutoDrawableBase.java:443)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:759)
    at com.jogamp.opengl.util.AWTAnimatorImpl.display(AWTAnimatorImpl.java:81)
    at com.jogamp.opengl.util.AnimatorBase.display(AnimatorBase.java:452)
    at com.jogamp.opengl.util.FPSAnimator$MainTask.run(FPSAnimator.java:178)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)
Instantiating hub object...
click
click
click
```

What should I try next?

**Comment by aj-ptw** [comment] 2018-04-23 03:46
Are you running the OpenBCI hub?

**Comment by trtnk** [comment] 2018-04-23 03:50
Yes I am. OpenBCIHub is running in administrator mode.  
Three processes run after running OpenBCIHub.

**Comment by neurochems** [comment] 2018-05-10 17:03
hi all, jumping in to say that i was having the same issues with the same conditions as marcelus and sidharthanup and a downgrade of processing from 3.3.7 to 3.3.6 also worked for me. thanks!!

**Closed** 2018-05-16 12:56 UTC
Labels: OpenBCIHub Related, bug, help wanted
