### ISSUE TITLE
Have problem with OPENBCI_GUI_processing but work properly in OpenBCI_GUI standalone

### ISSUE THREAD

**Issue by mfaizalamri** [OpenBCI/OpenBCI_GUI#321] opened 2018-04-04 09:04 UTC
Dear all,

I have problem when I tried to launch my OpenBCI_GUI processing version. I don't have any problem with the standalone version. 

The problem is like this figure, the protocol doesn't show up. I have launched my Open BCI Hub, but It said I didnt launch my openBCI_hub.

https://ibb.co/bHcVSH

but when I use the standalone version, it works

https://ibb.co/ciAZnH

And, when i try to use in another PC, Both work fine.

So, what the problem??

**Comment by aj-ptw** [comment] 2018-04-04 13:44
I think this is a duplicate of #316 closing for now, please follow that issue as we work through the problem

**Closed by aj-ptw** 2018-04-04 13:44 UTC
